name: Process and Deploy
on:
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            # First checkout the target repo (where we'll deploy)
            - name: Checkout Collection
              uses: actions/checkout@v4
              with:
                  repository: rtuszik/KoalaKeys-Collection

            # Then checkout the source repo into a subdirectory
            - name: Checkout KoalaKeys
              uses: actions/checkout@v4
              with:
                  repository: rtuszik/KoalaKeys
                  path: KoalaKeys

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install dependencies
              working-directory: KoalaKeys
              run: pip install -r requirements.txt

            - name: Copy input files
              run: |
                  mkdir -p KoalaKeys/cheatsheets
                  cp -r cheatsheets/* KoalaKeys/cheatsheets/

            - name: Run processing script
              working-directory: KoalaKeys
              run: python src/generate_cheatsheet.py

            - name: Copy output files
              run: |
                  mkdir -p output
                  cp -r KoalaKeys/output/* output/

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: output
                  branch: gh-pages
                  clean: true
                  force: true
