name: Process and Deploy
on:
    push:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout KoalaKeys
              uses: actions/checkout@v4
              with:
                  repository: rtuszik/KoalaKeys
                  path: KoalaKeys

            - name: Checkout Collection
              uses: actions/checkout@v4
              with:
                  repository: rtuszik/KoalaKeys-Collection
                  path: KoalaKeys-Collection
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install dependencies
              working-directory: KoalaKeys
              run: pip install -r requirements.txt

            - name: Copy input files
              run: |
                  mkdir -p KoalaKeys/cheatsheets
                  cp -r KoalaKeys-Collection/cheatsheets/* KoalaKeys/cheatsheets/

            - name: Run processing script
              working-directory: KoalaKeys
              run: python src/generate_cheatsheet.py

            - name: Copy output files
              run: |
                  mkdir -p KoalaKeys-Collection/output
                  cp -r KoalaKeys/output/* KoalaKeys-Collection/output/

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: KoalaKeys-Collection/output
                  branch: gh-pages
                  clean: true
                  force: true
                  token: ${{ secrets.GITHUB_TOKEN }}
